version: 2.1
# Use a package of configuration called an orb.

jobs:
  # create_infrastructure:
  #   docker:
  #     - image: amazon/aws-cli
  #   steps:
  #     - checkout
  #     - run:
  #         name: Create Cloudformation Stack
  #         command: |
  #           aws cloudformation deploy \
  #             --template-file template.yml \
  #             --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
  #             --region us-east-1
  # build: # Choose any name, such as `build`
  #   # The primary container, where your job's commands will run
  #   docker:
  #     - image: circleci/node:13.8.0
  #   steps:
  #     - checkout # check out the code in the project directory
  #     - run: echo "hello world" # run the `echo` command

  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout

      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            apk add --update ansible
            chmod 400 ansable.pem
            ansible-playbook main-remote.yml -i Inventory.txt  --private-key ansable.pem
# Sequential workflow
workflows:
  myWorkflow:
    jobs:
      - configure_infrastructure
