version: 2.1
# Use a package of configuration called an orb.

jobs:
  # create_infrastructure:
  #   docker:
  #     - image: amazon/aws-cli
  #   steps:
  #     - checkout
  #     - run:
  #         name: Create Cloudformation Stack
  #         command: |
  #           aws cloudformation deploy \
  #             --template-file template.yml \
  #             --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
  #             --region us-east-1
  # build: # Choose any name, such as `build`
  #   # The primary container, where your job's commands will run
  #   docker:
  #     - image: circleci/node:13.8.0
  #   steps:
  #     - checkout # check out the code in the project directory
  #     - run: echo "hello world" # run the `echo` command

  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          # You can get this ID in the section where you registered the SSH Key
          fingerprints: ["2a:d0:04:42:d2:de:33:57:c5:60:b4:f6:e1:c3:7c:44"]
      - run:
          name: Install Ansible
          command: |
            # Install Ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            apk add --update ansible
            ansible-playbook -i ansble/Inventory.txt ansble/main-remote.yml
# Sequential workflow
workflows:
  myWorkflow:
    jobs:
      - myjob1
      - create_infrastructure
